authors: [McMeze, Scarface01]
main: de.hardcorepvp.Main
version: 1.0.0
name: HCSystem

commands:
  craft:
  heal:
  feed:
  fix:
  ifix:
  enderchest:
  hat:
  stack:
  help:
  rename:
  pvp:
  invsee:
  goldswitch:
  ranking:
  ban:
  sell:
  giveall:
  spawner:
  tpa:
  tpaccept:
  tpdeny:
  tpahere:
  rank:
  stats:
  clan:
  more:
  skin:
  cmditem:
  world:
  vanish:
  youtube:
  teamspeak:
  skype:
  discord:
  spenden:
  bewerben:
  vote:
  globalmute:
  gamemode:
  near:
  excavator:
  tempban:
  unban:
  mute:
  tempmute:
  unmute:
  itemfilter: